"""LibraryUsers table

Revision ID: e2f3c1dd5390
Revises: 9f274bbfb01b
Create Date: 2022-10-25 14:27:43.632871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f3c1dd5390'
down_revision = '9f274bbfb01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('preferred_name', sa.String(length=64), nullable=True),
    sa.Column('email_address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('first_address', sa.String(length=255), nullable=True),
    sa.Column('second_address', sa.String(length=255), nullable=True),
    sa.Column('agency_code', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('extended_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_user_email_address'), 'library_user', ['email_address'], unique=True)
    op.create_index(op.f('ix_library_user_user_id'), 'library_user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_user_user_id'), table_name='library_user')
    op.drop_index(op.f('ix_library_user_email_address'), table_name='library_user')
    op.drop_table('library_user')
    # ### end Alembic commands ###
